apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: manish-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynewapp
  template:
    metadata:
      labels:
        app: mynewapp
    spec:
      containers:
      - name: mynewapp
        image: mnsharya/myapp:latest
        ports:
        - containerPort: 80
