apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: manish-namespace
spec:
  containers:
    - name: busybox
      image: radial/busyboxplus:curl
      command:
        - sleep
        - '3600'
