apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namepsace: manish-namespace
spec:
  selector:
    app: mynewapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # only reachable within the cluster network
